# Generated by Django 4.2 on 2023-11-11 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="assign_to",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previously_assigned_to", models.CharField(max_length=30)),
                ("currently_assigned_to", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ClientLeads",
            fields=[
                ("lead_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_by", models.CharField(max_length=30)),
                ("lead_name", models.CharField(max_length=30)),
                ("contact_number", models.BigIntegerField(blank=True, null=True)),
                ("door_number", models.CharField(blank=True, max_length=10, null=True)),
                ("street_name", models.CharField(blank=True, max_length=30, null=True)),
                ("area", models.CharField(blank=True, max_length=30, null=True)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("pincode", models.BigIntegerField(blank=True, null=True)),
                (
                    "enquiry_location",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gender", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "master_degree",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "master_specification",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("master_percentage", models.FloatField(blank=True, null=True)),
                (
                    "bachelor_degree",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "bachelor_specification",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("bachelor_percentage", models.FloatField(blank=True, null=True)),
                (
                    "course_enquired",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("source", models.CharField(max_length=30)),
                ("assigned_to", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "time_lead_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("technologies_known", models.TextField(default="")),
                ("level_of_lead", models.TextField(default="")),
                ("company_name", models.TextField(max_length=100)),
                (
                    "company_door_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "company_street_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "company_area",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "company_city",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "company_state",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("company_pincode", models.BigIntegerField(blank=True, null=True)),
                ("company_gstnumber", models.BigIntegerField(blank=True, null=True)),
                (
                    "company_field",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comapny_website", models.URLField(blank=True, null=True)),
                (
                    "company_contact_number",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("newlead", "New Lead"),
                            ("followup", "Follow Up"),
                            ("prospect", "Prospect"),
                            ("registered", "Registered"),
                            ("closed", "Closed"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Closed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(max_length=10)),
                ("history", models.TextField()),
                ("reason_for_closure", models.TextField()),
                (
                    "stage_of_closure",
                    models.CharField(
                        choices=[
                            ("newlead", "New Lead"),
                            ("followup", "Follow Up"),
                            ("prospect", "Prospect"),
                            ("registered", "Registered"),
                            ("closed", "Closed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("opportunities_in_future", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=200)),
                ("course_fees", models.BigIntegerField()),
                ("course_duration", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerLeads",
            fields=[
                ("lead_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_by", models.CharField(max_length=30)),
                ("lead_name", models.CharField(max_length=30)),
                ("contact_number", models.BigIntegerField(blank=True, null=True)),
                ("door_number", models.CharField(blank=True, max_length=10, null=True)),
                ("street_name", models.CharField(blank=True, max_length=30, null=True)),
                ("area", models.CharField(blank=True, max_length=30, null=True)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("pincode", models.BigIntegerField(blank=True, null=True)),
                (
                    "enquiry_location",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gender", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "master_degree",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "master_specification",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("master_percentage", models.FloatField(blank=True, null=True)),
                (
                    "bachelor_degree",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "bachelor_specification",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("bachelor_percentage", models.FloatField(blank=True, null=True)),
                (
                    "course_enquired",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("source", models.CharField(max_length=30)),
                ("assigned_to", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "time_lead_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("technologies_known", models.TextField(blank=True, default="")),
                (
                    "level_of_lead",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("newlead", "New Lead"),
                            ("followup", "Follow Up"),
                            ("prospect", "Prospect"),
                            ("registered", "Registered"),
                            ("closed", "Closed"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.TextField()),
                ("followup_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField()),
                ("walkin_date", models.DateField(blank=True, null=True)),
                ("walkin_time", models.TimeField(blank=True, null=True)),
                ("priority", models.SmallIntegerField(blank=True, null=True)),
                ("need_supervisor_attention", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Prospects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(max_length=20)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "preffered_course",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "preffered_batch_type",
                    models.CharField(
                        blank=True,
                        choices=[("weekdays", "Weekdays"), ("weekend", "Weekend")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preffered_batch_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "preffered_batch_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "preffered_class_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("expected_registration_date", models.DateField(blank=True, null=True)),
                ("visiting_time", models.TimeField(blank=True, null=True)),
                ("tentative_batch_start_date", models.DateField(blank=True, null=True)),
                (
                    "billing_amount",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "expected_collection",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "mode_of_payment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("upi", "UPI"),
                            ("bank transfer", "Bank Transfer"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registered",
            fields=[
                ("lead_id", models.CharField(max_length=30)),
                (
                    "registration_no",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "registration_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("course", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "batch_type",
                    models.CharField(
                        choices=[("weekdays", "Weekdays"), ("weekend", "Weekend")],
                        max_length=30,
                    ),
                ),
                (
                    "course_duration",
                    models.TextField(blank=True, max_length=30, null=True),
                ),
                ("tentative_start_date", models.DateField(blank=True, null=True)),
                ("tentative_end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "trainer_name",
                    models.TextField(blank=True, max_length=30, null=True),
                ),
                ("total_bill_amount", models.BigIntegerField(blank=True, null=True)),
                ("invoice_number", models.CharField(max_length=10)),
                ("advance_paid", models.BigIntegerField(blank=True, null=True)),
                (
                    "mode_of_payment",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("upi", "UPI"),
                            ("bank transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alternative_address", models.TextField(blank=True, null=True)),
                (
                    "alternative_contact_number",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "alternative_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Councellor,", "Councellor"),
                            ("Telecaller", "Telecaller"),
                            ("Manager", "Manager"),
                            ("Dumy", "Dumy"),
                        ],
                        max_length=50,
                    ),
                ),
                ("supervisor", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_image/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_id", models.BigIntegerField(blank=True, null=True)),
                ("lead_id", models.CharField(max_length=30)),
                ("employee_user_name", models.CharField(max_length=30)),
                (
                    "date_and_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
