# Generated by Django 4.2 on 2023-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closed",
            name="history",
        ),
        migrations.AddField(
            model_name="closed",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="closed",
            name="reason_for_closure",
            field=models.TextField(blank=True, null=True),
        ),
    ]
