# Generated by Django 4.2 on 2023-11-21 16:40

import Administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0002_remove_closed_history_closed_remarks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeActivities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=30)),
                (
                    "date_time",
                    models.DateTimeField(default=Administrator.models.default_datetime),
                ),
                ("employee_name", models.CharField(max_length=30)),
                ("call_count", models.PositiveIntegerField()),
                ("messages_count", models.PositiveIntegerField()),
                ("mail_count", models.PositiveIntegerField()),
                ("whatsapp_count", models.PositiveIntegerField()),
                ("counseling_count", models.PositiveIntegerField()),
                ("college_visit_count", models.PositiveIntegerField()),
                ("corporate_visit_count", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="clientleads",
            name="assigned_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("irayya", "irayya"),
                    ("arjun", "arjun"),
                    ("vidur", "vidur"),
                    ("aditya", "aditya"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientleads",
            name="source",
            field=models.CharField(
                choices=[
                    ("naukri", "Naukri"),
                    ("indeed", "Indeed"),
                    ("mail", "Mail"),
                    ("whatsapp", "Whatsapp"),
                    ("foundit", "Foundit"),
                    ("justdial", "Justdial"),
                    ("hirect", "Hirect"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customerleads",
            name="assigned_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("irayya", "irayya"),
                    ("arjun", "arjun"),
                    ("vidur", "vidur"),
                    ("aditya", "aditya"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerleads",
            name="source",
            field=models.CharField(
                choices=[
                    ("naukri", "Naukri"),
                    ("indeed", "Indeed"),
                    ("mail", "Mail"),
                    ("whatsapp", "Whatsapp"),
                    ("foundit", "Foundit"),
                    ("justdial", "Justdial"),
                    ("hirect", "Hirect"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("councellor", "Councellor"),
                    ("telecaller", "Telecaller"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="supervisor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("irayya", "irayya"),
                    ("arjun", "arjun"),
                    ("vidur", "vidur"),
                    ("aditya", "aditya"),
                ],
                max_length=50,
            ),
        ),
    ]
