# Generated by Django 4.2 on 2023-11-27 09:57

import Administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0004_empexcel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeActivitiesTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(default=Administrator.models.default_datetime),
                ),
                ("call_count_target", models.PositiveIntegerField(default=0)),
                ("messages_count_target", models.PositiveIntegerField(default=0)),
                ("mail_count_target", models.PositiveIntegerField(default=0)),
                ("whatsapp_count_target", models.PositiveIntegerField(default=0)),
                ("counseling_count_target", models.PositiveIntegerField(default=0)),
                ("college_visit_count_target", models.PositiveIntegerField(default=0)),
                (
                    "corporate_visit_count_target",
                    models.PositiveIntegerField(default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="call_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="college_visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="corporate_visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="counseling_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="mail_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="messages_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeactivities",
            name="whatsapp_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
