# Generated by Django 4.2 on 2023-11-28 06:52

import Administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Administrator", "0005_employeeactivitiestarget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientleads",
            name="time_lead_created",
            field=models.DateTimeField(default=Administrator.models.default_datetime),
        ),
        migrations.AlterField(
            model_name="customerleads",
            name="time_lead_created",
            field=models.DateTimeField(default=Administrator.models.default_datetime),
        ),
        migrations.AlterField(
            model_name="registered",
            name="registration_date",
            field=models.DateTimeField(default=Administrator.models.default_datetime),
        ),
    ]
